Oops assignments
SayanQi/ruby-assignments pull request #5
Opened 2024-01-31 06:49 UTC by SayanQi

2024-01-31 12:26 UTC, sabyasachi-palit requested changes

2024-02-01 09:24 UTC, sabyasachi-palit requested changes

2024-02-02 10:43 UTC, qisantanu commented on oops/Second.rb
> +  def access_global()
@sabyasachi-palit , please later check the file names, class, and variables names if it is following best practices

2024-02-06 05:31 UTC, sabyasachi-palit requested changes

2024-02-06 05:31 UTC, sabyasachi-palit commented on oops/tracker.rb
> +    @task_arr = []  # instance variable initialized with empty array
can you add attr_accessor for task_array and the related changes

2024-02-06 09:20 UTC, sabyasachi-palit approved these changes

2024-02-06 09:20 UTC, sabyasachi-palit commented
@SayanQi, please resolve conflicts

2024-02-06 09:44 UTC, merged